<?php
/**
 * Magnoolia project configuration
 *
 * GROUND RULES for this file:
 * - Do NOT invent prices. price => null until client provides confirmed hinnatabel.
 * - Do NOT invent private_yard_area. Use null until defined by architect.
 * - Do NOT invent terrace/balcony/storage. Use null until confirmed.
 * - Unit addresses are based on real project address structure from materials.
 * - Stage 1: Magnoolia tee 1 + 3 (keypunch: kevad 2027)
 * - Stage 2: Magnoolia tee 5, 7, 9, 11 (keypunch: kevad 2028)
 * - Status: available | reserved | sold | tbc
 * - plan_type: type-a (4-room 129.6m2) | type-b (5-room 143.2m2, corner)
 */

return [

    'project' => [
        'name'          => 'Magnoolia Kodud',
        'brand_name'    => 'Magnoolia',
        'slogan'        => 'Ridaelamu mugavus. Eramaja privaatsus.',
        'location'      => 'Vaela küla, Kiili vald, Harjumaa',
        'completion_1'  => 'kevad 2027',
        'completion_2'  => 'kevad 2028',
        'homes_count'   => 19,
        'energy_class'  => 'A',
        'developer'     => 'Estlanda OÜ',
        'contact_email' => 'diana@estlanda.ee',
        'contact_phone' => '+37258164078',
    ],

    'stages' => [
        1 => [
            'label'      => 'I etapp',
            'buildings'  => ['Magnoolia tee 1', 'Magnoolia tee 3'],
            'completion' => 'kevad 2027',
            'homes'      => 7,
        ],
        2 => [
            'label'      => 'II etapp',
            'buildings'  => ['Magnoolia tee 5', 'Magnoolia tee 7', 'Magnoolia tee 9', 'Magnoolia tee 11'],
            'completion' => 'kevad 2028',
            'homes'      => 12,
        ],
    ],

    'navigation' => [
        ['id' => 'about',       'label_key' => 'magnoolia.nav.about'],
        ['id' => 'hinnad',      'label_key' => 'magnoolia.nav.homes'],
        ['id' => 'asendiplaan', 'label_key' => 'magnoolia.nav.masterplan'],
        ['id' => 'ehitusinfo',  'label_key' => 'magnoolia.nav.building'],
        ['id' => 'kontakt',     'label_key' => 'magnoolia.nav.contact'],
    ],

    'facts' => [
        ['value' => '19',       'label' => 'kodu',           'icon' => 'home'],
        ['value' => 'A',        'label' => 'energiaklass',   'icon' => 'energy'],
        ['value' => '~129 m2',  'label' => 'elamispind',     'icon' => 'flooring'],
        ['value' => 'kevad 2027', 'label' => 'I etapp',      'icon' => 'calendar'],
        ['value' => '20 min',   'label' => 'Tallinnast',     'icon' => 'location'],
    ],

    /*
     * UNIT DATA
     * Stage 1: Magnoolia tee 1 (4 homes) + Magnoolia tee 3 (3 homes) = 7 homes, kevad 2027
     * Stage 2: Magnoolia tee 5-11 (3 homes each) = 12 homes, kevad 2028
     * Total: 19 homes
     *
     * plan_type:
     *   type-a = 4-room, net 129.6 m2, end sections of building
     *   type-b = 5-room, net 143.2 m2, corner/end units (wider terrace)
     *
     * terrace_area / balcony_area / storage_area / private_yard_area:
     *   => null until confirmed by architect. Do NOT invent.
     *
     * price => null until client provides hinnatabel. Do NOT invent.
     */
    'units' => [
        // ── STAGE 1 / I ETAPP — Magnoolia tee 1 ──────────────────────────
        [
            'id'               => 'tee-1-1',
            'address'          => 'Magnoolia tee 1/1',
            'building'         => 'Magnoolia tee 1',
            'section'          => '1/1',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null, // TODO: confirm with architect
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null, // TODO: hinnatabel from client
            'status'           => 'available',
            'masterplan_key'   => 'tee-1-pos-1', // TODO: map after SVG/EXR
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-1-2',
            'address'          => 'Magnoolia tee 1/2',
            'building'         => 'Magnoolia tee 1',
            'section'          => '1/2',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-1-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-1-3',
            'address'          => 'Magnoolia tee 1/3',
            'building'         => 'Magnoolia tee 1',
            'section'          => '1/3',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'reserved',
            'masterplan_key'   => 'tee-1-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-1-4',
            'address'          => 'Magnoolia tee 1/4',
            'building'         => 'Magnoolia tee 1',
            'section'          => '1/4',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-b',
            'rooms'            => 5,
            'net_area'         => 143.2,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-1-pos-4',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        // ── STAGE 1 / I ETAPP — Magnoolia tee 3 ──────────────────────────
        [
            'id'               => 'tee-3-1',
            'address'          => 'Magnoolia tee 3/1',
            'building'         => 'Magnoolia tee 3',
            'section'          => '3/1',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-3-pos-1',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-3-2',
            'address'          => 'Magnoolia tee 3/2',
            'building'         => 'Magnoolia tee 3',
            'section'          => '3/2',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'reserved',
            'masterplan_key'   => 'tee-3-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-3-3',
            'address'          => 'Magnoolia tee 3/3',
            'building'         => 'Magnoolia tee 3',
            'section'          => '3/3',
            'stage'            => 1,
            'completion'       => 'kevad 2027',
            'plan_type'        => 'type-b',
            'rooms'            => 5,
            'net_area'         => 143.2,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-3-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        // ── STAGE 2 / II ETAPP — Magnoolia tee 5 ─────────────────────────
        [
            'id'               => 'tee-5-1',
            'address'          => 'Magnoolia tee 5/1',
            'building'         => 'Magnoolia tee 5',
            'section'          => '5/1',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'sold',
            'masterplan_key'   => 'tee-5-pos-1',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-5-2',
            'address'          => 'Magnoolia tee 5/2',
            'building'         => 'Magnoolia tee 5',
            'section'          => '5/2',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-5-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-5-3',
            'address'          => 'Magnoolia tee 5/3',
            'building'         => 'Magnoolia tee 5',
            'section'          => '5/3',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-5-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        // ── STAGE 2 / II ETAPP — Magnoolia tee 7 ─────────────────────────
        [
            'id'               => 'tee-7-1',
            'address'          => 'Magnoolia tee 7/1',
            'building'         => 'Magnoolia tee 7',
            'section'          => '7/1',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-7-pos-1',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-7-2',
            'address'          => 'Magnoolia tee 7/2',
            'building'         => 'Magnoolia tee 7',
            'section'          => '7/2',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'reserved',
            'masterplan_key'   => 'tee-7-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-7-3',
            'address'          => 'Magnoolia tee 7/3',
            'building'         => 'Magnoolia tee 7',
            'section'          => '7/3',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-7-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        // ── STAGE 2 / II ETAPP — Magnoolia tee 9 ─────────────────────────
        [
            'id'               => 'tee-9-1',
            'address'          => 'Magnoolia tee 9/1',
            'building'         => 'Magnoolia tee 9',
            'section'          => '9/1',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-9-pos-1',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-9-2',
            'address'          => 'Magnoolia tee 9/2',
            'building'         => 'Magnoolia tee 9',
            'section'          => '9/2',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'reserved',
            'masterplan_key'   => 'tee-9-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-9-3',
            'address'          => 'Magnoolia tee 9/3',
            'building'         => 'Magnoolia tee 9',
            'section'          => '9/3',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-9-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        // ── STAGE 2 / II ETAPP — Magnoolia tee 11 ────────────────────────
        [
            'id'               => 'tee-11-1',
            'address'          => 'Magnoolia tee 11/1',
            'building'         => 'Magnoolia tee 11',
            'section'          => '11/1',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-11-pos-1',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-11-2',
            'address'          => 'Magnoolia tee 11/2',
            'building'         => 'Magnoolia tee 11',
            'section'          => '11/2',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-a',
            'rooms'            => 4,
            'net_area'         => 129.6,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-11-pos-2',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
        [
            'id'               => 'tee-11-3',
            'address'          => 'Magnoolia tee 11/3',
            'building'         => 'Magnoolia tee 11',
            'section'          => '11/3',
            'stage'            => 2,
            'completion'       => 'kevad 2028',
            'plan_type'        => 'type-b',
            'rooms'            => 5,
            'net_area'         => 143.2,
            'terrace_area'     => null,
            'balcony_area'     => null,
            'storage_area'     => null,
            'private_yard_area'=> null,
            'parking'          => 2,
            'price'            => null,
            'status'           => 'available',
            'masterplan_key'   => 'tee-11-pos-3',
            'floorplan_1'      => null,
            'floorplan_2'      => null,
        ],
    ],

    'statuses' => [
        'available' => 'Vaba',
        'reserved'  => 'Broneeritud',
        'sold'      => 'Müüdud',
        'tbc'       => 'Täpsustamisel',
    ],

    'media' => [
        'hero_video'  => null,
        'hero_poster' => null,
        'logo_light'  => null,
        'logo_dark'   => null,
        'renders'     => [],
        'masterplan'  => null,
    ],

    'seo' => [
        // Leave null until final production domain is confirmed by client.
        'canonical_base' => env('MAGNOOLIA_CANONICAL_BASE', null),
        'og_image'       => 'assets/images/magnoolia/Cam001.0000.jpg',
    ],

];
