{{-- SOURCE: php-template/parts/home1/projects.php | class: best-project-one section-space-top (video/gallery) --}}
    <section class="best-project-one section-space-top">
        <div class="sec-title text-center">
            <div class="sec-title__top justify-content-center">
                <span class="line-left"></span>
                <h6 class="sec-title__tagline bw-split-in-right">Our BEST PROJECTS</h6>
                <span class="line-right"></span>
            </div>
            <h3 class="sec-title__title bw-split-in-left">Property Investment Assisting <br> Projects House lucrative.</h3>
        </div>
        <div class="best-project-one__carousel zoomvilla-owl__carousel owl-carousel owl-theme wow fadeInUp" data-wow-duration="1500ms" data-wow-delay="300ms" data-owl-options='{"items":2,"margin":0,"loop":true,"smartSpeed":700,"center":true,"nav":true,"dots":false,"navText":["<i class=\"icon-angle-small-right\"></i>","<i class=\"icon-angle-small-right\"></i>"],"autoplay":false,"responsive":{"0":{"items":1},"768":{"items":1},"992":{"items":2},"1300":{"items":2}}}'>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-1.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-1.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-2.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-2.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-3.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-3.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-1.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-1.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-2.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-2.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
            <div class="item"><div class="best-project-one__item"><img src="{{ asset('assets/images/resources/best-project-1-3.jpg') }}" alt="image"><div class="best-project-one__item__popup"><a href="{{ asset('assets/images/resources/best-project-1-3.jpg') }}" class="img-popup"><i class="icon-zoom-1"></i></a><a href="https://www.youtube.com/watch?v=aO_kPW39um8" class="video-popup"><i class="icon-play-1"></i></a></div></div></div>
        </div>
    </section>